### ISSUE TITLE
Typo in the primitive keras.Sequential.LSTMTimeSeriesRegressor

### ISSUE THREAD

**Issue by DanielCalvoCerezo** [HDI-Project/MLPrimitives#176] opened 2019-06-13 14:12 UTC
* MLPrimitives version:0.1.10
* Python version:N/A
* Operating System:N/A

### Description

There is a typo in line 74 of MLPrimitives/mlprimitives/jsons/keras.Sequential.LSTMTimeSeriesRegressor.json 
It says bastch_size and should say batch_size. Otherwise, the batch size of the training cannot be tuned

### What I Did

```
Simply correct the typo and it works :)
```

**Comment by csala** [comment] 2019-06-17 00:07
Thanks for pointing it out @DanielCalvoCerezo !
Would you mind doing a PR with the change?

**Comment by DanielCalvoCerezo** [comment] 2019-06-17 10:12
Hi @csala 
I am trying to create a new branch to add a PR with the fix but I cannot. I do not know if I need to be added to the project as collaborator or it is a matter of my setup here (our proxy is really picky)
Sorry for the trouble

**Comment by csala** [comment] 2019-06-17 13:58
Hi @DanielCalvoCerezo 
You probably need to create a fork of the project under your account and then make the PR from there.

You can see the exact instructions about the development setup here: https://hdi-project.github.io/MLPrimitives/readme.html#install-for-development

You can also have a look at the contributing step-by-step guide for this scenario: https://hdi-project.github.io/MLPrimitives/community/annotations.html#modifying-an-existing-annotation
Since we have already discussed this and the issue is already assigned to you, you can jump directly to point 4 of this list.

Also, thanks for willing to contribute! :-)

**Comment by csala** [comment] 2019-06-22 14:28
Closed via #178

**Closed by csala** 2019-06-22 14:28 UTC
Labels: Approved, bug
